### 1. Create a 1D array of numbers from 0 to 9

In [2]:
# Importing NumPy library
import numpy as np

In [3]:
#one_d = np.array([0,1,2,3,4,5,6,7,8,9])
one_d = np.arange(10)
print(one_d)

[0 1 2 3 4 5 6 7 8 9]


### 2. Create a 3x3 NumPy array of all Boolean value Trues

In [4]:
#arr = np.array([1,1,1,1,1,1,1,1,1], dtype=bool)
arr = np.random.choice([True],size=9)
array_bool = arr.reshape(3,3)
print(array_bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 3. Extract all odd numbers from array of 1-10

In [5]:
#arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr = np.arange(1,11)
odd_num = []
for x in arr:
    if x%2 == 0:
        odd_num.append(x)
print(odd_num)

[2, 4, 6, 8, 10]


### 4. Replace all odd numbers in an array of 1-10 with the value -1

In [6]:
arr = np.arange(1,11)
arr = np.where(arr%2==1, -1, arr)
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


### 5. Convert a 1D array to a 2D array with 2rows

In [7]:
one_d_arr = np.array([0,1,2,3,4,5,6,7,8,9])
col = int(len(one_d_arr)/2)
two_d_arr = one_d_arr.reshape(2,col)
#two_d_arr = one_d_arr.reshape(2,5)
print(two_d_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 6. Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals

In [10]:
a = np.arange(2,6) # [2,3,4,5]
b = np.arange(6,10) # [6,7,8,9]
c = np.dot(a,b)
sum =np.sum(c) 
#print(c)
print(sum)

110
